const ActionTypes = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',
  SET_PAGE: 'SET_PAGE_PRODUCTS',
  SET_LIMIT: 'SET_LIMIT_PRODUCTS',
  SET_SORT: 'SET_SORT_PRODUCTS',
  SET_ORDENATION: 'SET_ORDENATION_PRODUCTS',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT_PRODUCTS',
};

export default ActionTypes;
