const ActionTypes = {
  POST_LOGIN: 'POST_LOGIN',
  POST_LOGIN_SUCCESS: 'POST_LOGIN_SUCCESS',
  POST_LOGIN_ERROR: 'POST_LOGIN_ERROR',
  POST_REGISTER: 'POST_REGISTER',
  POST_REGISTER_SUCCESS: 'POST_REGISTER_SUCCESS',
  POST_REGISTER_ERROR: 'POST_REGISTER_ERROR',
};

export default ActionTypes;
